/* eslint-disable @typescript-eslint/no-explicit-any */

export interface SoundConfig {
  bgm?: string;        // path relative to /public, e.g. "sounds/bgm/ocean_ambient.mp3"
  bgm_volume?: number; // 0–1, default 0.2
}

export interface CardConfig {
  card_id: string;
  card_type: "general" | "read_with_me" | "story_writer";
  title: string;
  subtitle: string;
  cover_image: string;
  persona_name: string;
  prompt_file: string | null;
  system_prompt?: string;
  book_data_path: string | null;
  voice_openai: string;
  temperature: number;
  active: boolean;
  sounds?: SoundConfig;
  use_realtime?: boolean;
  voice_provider?: 'openai' | 'elevenlabs';
  elevenlabs_voice_id?: string;
  llm_model?: string;
  is_listen_only?: boolean;
  disable_thinking_cue?: boolean;
  use_json_mode?: boolean;
  has_timer?: boolean;
  timer_seconds?: number;
}

export type ReadingSessionPhase = "PRE" | "DURING_DIALOGIC" | "POST" | "END";

export interface ReadingPhasePrompts {
  pre: string;
  during_dialogic: string;
  post: string;
}

export interface ReadingSessionState {
  phase: ReadingSessionPhase;
  currentPageIndex: number; // 0-indexed across book.pages
  totalPages: number;
  [key: string]: any; // Allow arbitrary state for games
}

// Structures generated by prompt_01_analyzer.md
export interface BookMetadata {
  title: string;
  total_pages: number;
  themes: string[];
  [key: string]: any;
}

export interface BookPage {
  page_number: number;
  illustration_description: string;
  text: string;
  tts_read_script: string;
  key_vocabulary: any[];
  crowd_questions: any[];
  echo_reading: any;
}

export interface BookData {
  book_id: string;
  book_metadata: BookMetadata;
  pre_reading: any;
  pages: BookPage[];
  post_reading: any;
}

// ─── Parent App Types ────────────────────────────────────────────────────────

export interface ChildProfile {
  profile_id: string;
  name: string;
  birth_date: string;        // "YYYY-MM-DD"
  avatar: string;            // emoji or image path
  interests: string[];       // ["우주", "공룡", ...]
  language: "ko" | "en" | "both";
  daily_limit_minutes: number; // 0 = 무제한
  allowed_card_ids: string[]; // 빈 배열 = 전체 허용
  created_at: string;
}

export interface SessionLog {
  session_id: string;
  profile_id: string;
  card_id: string;
  card_title: string;
  card_type: string;
  started_at: string;        // ISO string
  ended_at: string;          // ISO string
  duration_seconds: number;
  topics_covered: string[];
  child_questions: string[];
  highlighted_words: string[];
  pages_completed?: number;
  game_results?: {
    total_rounds: number;
    correct_answers: number;
    hints_used: number;
  };
  talk_guide_generated: boolean;
}

export interface TalkGuide {
  guide_id: string;
  profile_id: string;
  session_id: string;
  card_id: string;
  card_title: string;
  generated_at: string;
  title: string;
  summary_for_parent: string;
  child_highlight: string;
  conversation_starters: {
    question: string;
    why_this_works: string;
  }[];
  offline_activities: string[];
  book_recommendations: { title: string; reason: string }[];
  parent_acknowledged: boolean;
  conversation_happened: boolean;
}

export interface DailyUsageSummary {
  date: string;              // "YYYY-MM-DD"
  total_minutes: number;
  session_count: number;
  cards_used: { card_id: string; card_title: string; minutes: number }[];
}

export interface WeeklyUsageSummary {
  days: DailyUsageSummary[];
  total_minutes: number;
  total_sessions: number;
  top_cards: { card_id: string; card_title: string; minutes: number }[];
}

// ─── Prompt versioning types ─────────────────────────────────────────────────
export interface PromptVersion {
  id: string;
  content: string;
  label: string;
  created_at: string;
}

export interface PromptVersionFile {
  card_id: string;
  prompt_key: string; // e.g. "default", "pre", "during_dialogic", "post"
  active_version_id: string;
  versions: PromptVersion[];
}
