/* eslint-disable @typescript-eslint/no-explicit-any */

export interface SoundConfig {
  bgm?: string;        // path relative to /public, e.g. "sounds/bgm/ocean_ambient.mp3"
  bgm_volume?: number; // 0–1, default 0.2
}

export interface CardConfig {
  card_id: string;
  card_type: "general" | "read_with_me";
  title: string;
  subtitle: string;
  cover_image: string;
  persona_name: string;
  prompt_file: string | null;
  system_prompt?: string;
  book_data_path: string | null;
  voice_openai: string;
  temperature: number;
  active: boolean;
  sounds?: SoundConfig;
  use_realtime?: boolean;
  voice_provider?: 'openai' | 'elevenlabs';
  elevenlabs_voice_id?: string;
  llm_model?: string;
}

export type ReadingSessionPhase = "PRE" | "DURING_DIALOGIC" | "POST" | "END";

export interface ReadingPhasePrompts {
  pre: string;
  during_dialogic: string;
  post: string;
}

export interface ReadingSessionState {
  phase: ReadingSessionPhase;
  currentPageIndex: number; // 0-indexed across book.pages
  totalPages: number;
}

// Structures generated by prompt_01_analyzer.md
export interface BookMetadata {
  title: string;
  total_pages: number;
  themes: string[];
  [key: string]: any;
}

export interface BookPage {
  page_number: number;
  illustration_description: string;
  text: string;
  tts_read_script: string;
  key_vocabulary: any[];
  crowd_questions: any[];
  echo_reading: any;
}

export interface BookData {
  book_id: string;
  book_metadata: BookMetadata;
  pre_reading: any;
  pages: BookPage[];
  post_reading: any;
}

// Prompt versioning types
export interface PromptVersion {
  id: string;
  content: string;
  label: string;
  created_at: string;
}

export interface PromptVersionFile {
  card_id: string;
  prompt_key: string; // e.g. "default", "pre", "during_dialogic", "post"
  active_version_id: string;
  versions: PromptVersion[];
}
